# Generated by Django 6.0.1 on 2026-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
